### ISSUE TITLE
Wie heißt das von der OMG festgelegte Meta‐Meta‐Modell für MDA?

### ISSUE THREAD

**Issue by SirMoM** [SirMoM/Softwaretechnologie#54]
- [x] Wie heißt das von der OMG festgelegte Meta‐Meta‐Modell für MDA?
> Meta Object Facility also MOF 
- [x] Was ist ein PIM?
> PIM (platform independent model) basiert auf einem formalen Modell
> Also ein Model das plattform unabhänig ist
- [x] Was ist ein PSM?
> PSM (platform independent model) basiert auf einem formalen Modell und verfeinert PIM
> Also ein Model das für ein Plattform spezifiziert ist.
- [x] Unterschied?
> Das eine ist für eine Platform / Sprache / Gerät das andere für "alle"
- [x] Das eine ist specifischer als das andere?
> PSM ist speuifischer als andere
- [x] Was ist OCL?
> OCL (Object Constraint Language)  MOF basiert, 
> Pre- und Postcondtions sowie Invarianten können mit OCL (ebenfalls MOF basiert) definiert werden.
> Die Object Constraint Language (OCL) ist eine deklarative Sprache, die Regeln beschreibt, die für UML-> Modelle (Unified Modeling Language) gelten, die von IBM entwickelt wurden. Sie ist jetzt Teil des  UML-Standards.
